#!/usr/bin/env bash
# Shows information about subdomains.

domain_information() {
    local domain="$1"
    local subdomain="$2"
    local line
    line=$(dig "$subdomain"."$domain" +noall +answer | awk '{print $5}')
    if [ -z "$line" ]; then
        echo "The subdomain $subdomain does not exist or is not an A record"
    else
        echo "The subdomain $subdomain is a A record and points to $line"
    fi
}

if [ "$#" -eq 1 ]; then
    domain_information "$1" "www"
    domain_information "$1" "lb-01"
    domain_information "$1" "web-01"
    domain_information "$1" "web-02"
elif [ "$#" -eq 2 ]; then
    domain_information "$1" "$2"
fi

