#!/usr/bin/env bash
# Update the package lists for upgrades and new package installations
sudo apt-get update -y

# Install Nginx
sudo apt-get install nginx -y

# Start Nginx
sudo service nginx start

# Create a simple HTML file
echo "Hello World!" > /var/www/html/index.html

# Restart Nginx to apply the changes (without using systemctl)
sudo service nginx restart

