#!/usr/bin/env bash
# configuring web-01 to have an HTTP response header

# updating packages
sudo apt-get update
sudo apt-get install -y nginx

# creating index page
echo "Hello World!" | sudo tee /var/www/html/index.html

# redirection
new_string="server_name _;\n\trewrite^\/redirect_me https:\/\/github.com\/tosinkuzzy permanent;"

sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

# creating a custom error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# custom HTTP response header
sudo sed -i "server_name _;/a add_header X-Server-By $HOSTNAME;" /etc/nginx/sites-enabled/default

# Test for syntax errors
sudo nginx -t

# Restart nginx
sudo service nginx restart
