#!/usr/bin/env bash
# script that displays the content of the file /etc/passwd.
# script only display:
# username
# user id
# Home directory path for the user
 
while IFS="" read -r line || [ -n "$line" ]
do
    echo "$line" | cut -d ":" -f 1,3,6
done < "/etc/passwd"
